const films = [
  {
    title: "The Shawshank Redemption",
    titleSlug: "the-shawshank-redemption",
    rating: "15",
    runtime: 142,
    releasedate: 1994,
    description: "Two imprisoned men bond over a number of years...",
    genre: ["Drama"],
    image: {
      url: "https://res.cloudinary.com/du5v06qai/image/upload/v1689765837/iCinema/y5nn7x2ks8lpiwr82kvn.png",
      filename: "iCinema/y5nn7x2ks8lpiwr82kvn",
    },
    stock: 5,
  },
  {
    title: "The Godfather",
    titleSlug: "the-godfather",
    rating: "18",
    runtime: 175,
    releasedate: 1972,
    description: "The aging patriarch of an organized crime dynasty...",
    genre: ["Crime", "Drama"],
    image: {
      url: "https://res.cloudinary.com/du5v06qai/image/upload/v1689765837/iCinema/y5nn7x2ks8lpiwr82kvn.png",
      filename: "iCinema/y5nn7x2ks8lpiwr82kvn",
    },
    stock: 8,
  },
  {
    title: "Pulp Fiction",
    titleSlug: "pulp-fiction",
    rating: "18",
    runtime: 154,
    releasedate: 1994,
    description: "The lives of two mob hitmen, a boxer, a gangster...",
    genre: ["Crime", "Drama"],
    image: {
      url: "https://res.cloudinary.com/du5v06qai/image/upload/v1689765837/iCinema/y5nn7x2ks8lpiwr82kvn.png",
      filename: "iCinema/y5nn7x2ks8lpiwr82kvn",
    },
    stock: 3,
  },
  {
    title: "Inception",
    titleSlug: "inception",
    rating: "12A",
    runtime: 148,
    releasedate: 2010,
    description: "A thief who steals corporate secrets through the use...",
    genre: ["Action", "Adventure", "Science Fiction"],
    image: {
      url: "https://res.cloudinary.com/du5v06qai/image/upload/v1689765837/iCinema/y5nn7x2ks8lpiwr82kvn.png",
      filename: "iCinema/y5nn7x2ks8lpiwr82kvn",
    },
    stock: 10,
  },
  {
    title: "The Dark Knight",
    titleSlug: "the-dark-knight",
    rating: "12A",
    runtime: 152,
    releasedate: 2008,
    description:
      "When the menace known as the Joker emerges from his mysterious past...",
    genre: ["Action", "Crime", "Drama"],
    image: {
      url: "https://res.cloudinary.com/du5v06qai/image/upload/v1689765837/iCinema/y5nn7x2ks8lpiwr82kvn.png",
      filename: "iCinema/y5nn7x2ks8lpiwr82kvn",
    },
    stock: 6,
  },
  {
    title: "Fight Club",
    titleSlug: "fight-club",
    rating: "18",
    runtime: 139,
    releasedate: 1999,
    description: "An insomniac office worker and a devil-may-care soapmaker...",
    genre: ["Drama"],
    image: {
      url: "https://res.cloudinary.com/du5v06qai/image/upload/v1689765837/iCinema/y5nn7x2ks8lpiwr82kvn.png",
      filename: "iCinema/y5nn7x2ks8lpiwr82kvn",
    },
    stock: 4,
  },
  {
    title: "The Matrix",
    titleSlug: "the-matrix",
    rating: "15",
    runtime: 136,
    releasedate: 1999,
    description:
      "A computer hacker learns from mysterious rebels about the true nature...",
    genre: ["Action", "Science Fiction"],
    image: {
      url: "https://res.cloudinary.com/du5v06qai/image/upload/v1689765837/iCinema/y5nn7x2ks8lpiwr82kvn.png",
      filename: "iCinema/y5nn7x2ks8lpiwr82kvn",
    },
    stock: 7,
  },
  {
    title: "Goodfellas",
    titleSlug: "goodfellas",
    rating: "18",
    runtime: 146,
    releasedate: 1990,
    description: "The story of Henry Hill and his life in the mob...",
    genre: ["Crime", "Drama"],
    image: {
      url: "https://res.cloudinary.com/du5v06qai/image/upload/v1689765837/iCinema/y5nn7x2ks8lpiwr82kvn.png",
      filename: "iCinema/y5nn7x2ks8lpiwr82kvn",
    },
    stock: 2,
  },
  {
    title: "Forrest Gump",
    titleSlug: "forrest-gump",
    rating: "12",
    runtime: 142,
    releasedate: 1994,
    description: "The presidencies of Kennedy and Johnson, the Vietnam War...",
    genre: ["Drama", "Romance"],
    image: {
      url: "https://res.cloudinary.com/du5v06qai/image/upload/v1689765837/iCinema/y5nn7x2ks8lpiwr82kvn.png",
      filename: "iCinema/y5nn7x2ks8lpiwr82kvn",
    },

    stock: 9,
  },
  {
    title: "The Lord of the Rings The Fellowship of the Ring",
    titleSlug: "the-lord-of-the-rings-the-fellowship-of-the-ring",
    rating: "PG",
    runtime: 178,
    releasedate: 2001,
    description: "A meek Hobbit from the Shire and eight companions...",
    genre: ["Action", "Adventure", "Drama", "Fantasy"],
    image: {
      url: "https://res.cloudinary.com/du5v06qai/image/upload/v1689765837/iCinema/y5nn7x2ks8lpiwr82kvn.png",
      filename: "iCinema/y5nn7x2ks8lpiwr82kvn",
    },

    stock: 12,
  },
];

module.exports = films;
